package(default_visibility = ["//visibility:public"])

cc_test(
    name = "queue_test",
    srcs = ["queue_test.cc"],
    deps = [
        "//:lib",
        "@com_google_googletest//:gtest",
        "@com_google_googletest//:gtest_main",
    ],
)