cc_test(
    name = "shared_data_test",
    srcs = ["shared_data_test.cc"],
    deps = [
        "//:lib",
        "@com_google_googletest//:gtest",
        "@com_google_googletest//:gtest_main",
    ],
)
